# Generated by Django 3.1.5 on 2021-01-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBDCompany',
            fields=[
                ('company_id', models.CharField(db_column='company_id', max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='company_name', max_length=255)),
                ('company_type', models.CharField(db_column='company_type', max_length=255)),
                ('company_objective', models.CharField(db_column='company_objective', max_length=240)),
            ],
            options={
                'verbose_name': 'Scraped Company',
                'verbose_name_plural': 'Scraped Companies',
                'db_table': 'dbd_scraped_company',
                'managed': True,
            },
        ),
    ]
