version: "3.2"
services:
  pip:
    build:
      context: ./
      dockerfile: python.dockerfile
    container_name: dbdv3_backend
    tty: true
    restart: always
    working_dir: /backend
    volumes:
      - ./backend:/backend
    ports:
      - 1200:8000
    networks:
      - proxy-db
  angular:
    build:
      context: ./
      dockerfile: frontend/my-app/Dockerfile
    container_name: dbdv3_frontend
    ports:
      - 8010:80
    depends_on:
      - pip

networks:
  proxy-db:
    external:
      name: proxy-db
