# Generated by Django 3.1.5 on 2021-03-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, db_column='company_id', max_length=20, null=True)),
                ('year', models.CharField(blank=True, db_column='year', max_length=20, null=True)),
                ('amount', models.CharField(blank=True, db_column='amount', max_length=40, null=True)),
                ('change', models.CharField(blank=True, db_column='change', max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Scraped Posit Year Detail',
                'verbose_name_plural': 'Scraped Posit Year Details',
                'db_table': 'posit_year_detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FinancialPosition',
            fields=[
                ('company_id', models.CharField(db_column='company_id', default='Null', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('accounts_receive', models.ManyToManyField(blank=True, db_column='accounts_receive', max_length=255, related_name='accounts_receive', to='finan_posit_app.PositYear')),
                ('equity', models.ManyToManyField(blank=True, db_column='equity', max_length=255, related_name='equity', to='finan_posit_app.PositYear')),
                ('inventory', models.ManyToManyField(blank=True, db_column='inventory', max_length=255, related_name='inventory', to='finan_posit_app.PositYear')),
                ('proper_plant_equip', models.ManyToManyField(blank=True, db_column='proper_plant_equip', max_length=255, related_name='proper_plant_equip', to='finan_posit_app.PositYear')),
                ('t_assets', models.ManyToManyField(blank=True, db_column='t_assets', max_length=255, related_name='t_assets', to='finan_posit_app.PositYear')),
                ('t_curr_asset', models.ManyToManyField(blank=True, db_column='t_curr_asset', max_length=255, related_name='t_curr_asset', to='finan_posit_app.PositYear')),
                ('t_curr_liab', models.ManyToManyField(blank=True, db_column='t_curr_liab', max_length=255, related_name='t_curr_liab', to='finan_posit_app.PositYear')),
                ('t_liab', models.ManyToManyField(blank=True, db_column='t_liab', max_length=255, related_name='t_liab', to='finan_posit_app.PositYear')),
                ('t_liab_and_equity', models.ManyToManyField(blank=True, db_column='t_liab_and_equity', max_length=255, related_name='t_liab_and_equity', to='finan_posit_app.PositYear')),
                ('t_nonCurr_asset', models.ManyToManyField(blank=True, db_column='t_nonCurr_asset', max_length=255, related_name='t_nonCurr_asset', to='finan_posit_app.PositYear')),
                ('t_nonCurr_liab', models.ManyToManyField(blank=True, db_column='t_nonCurr_liab', max_length=255, related_name='t_nonCurr_liab', to='finan_posit_app.PositYear')),
            ],
            options={
                'verbose_name': 'Scraped Financial Position',
                'verbose_name_plural': 'Scraped Financial Postions',
                'db_table': 'dbd_finian_posit',
                'managed': True,
            },
        ),
    ]
