# Generated by Django 3.1.5 on 2021-03-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBDCompany_Eng',
            fields=[
                ('company_id', models.CharField(db_column='company_id', default='Null', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(db_column='company_name', default='Null', max_length=255)),
                ('company_type', models.CharField(db_column='company_type', default='Null', max_length=255)),
                ('company_status', models.CharField(db_column='company_status', default='Null', max_length=255)),
                ('company_objective', models.TextField(db_column='company_objective', default='Null')),
                ('company_directors', models.TextField(db_column='company_directors')),
                ('company_bussiness_type', models.TextField(db_column='company_bussiness_type', default='Null')),
                ('company_bussiness_type_code', models.CharField(db_column='company_bussiness_code', default='Null', max_length=20)),
                ('company_address', models.TextField(db_column='company_address', default='Null')),
                ('company_tel', models.CharField(db_column='company_tel', default='Null', max_length=255)),
                ('company_fax', models.CharField(db_column='company_fax', default='Null', max_length=255)),
                ('company_website', models.CharField(db_column='company_website', default='Null', max_length=255)),
                ('company_email', models.CharField(db_column='company_email', default='Null', max_length=255)),
                ('company_last_registered_id', models.CharField(db_column='company_last_registered_id', default='Null', max_length=20)),
                ('company_fiscal_year', models.CharField(db_column='company_fiscal_year', default='Null', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_changed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Scraped Eng Company',
                'verbose_name_plural': 'Scraped Eng Companies',
                'db_table': 'dbd_scraped_eng',
                'managed': True,
            },
        ),
    ]
