# Generated by Django 3.1.5 on 2021-01-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_eng_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_address',
            field=models.TextField(db_column='company_address'),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_bussiness_type',
            field=models.TextField(db_column='company_bussiness_type'),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_directors',
            field=models.TextField(db_column='company_directors'),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_objective',
            field=models.TextField(db_column='company_objective'),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_street',
            field=models.TextField(db_column='company_street'),
        ),
    ]
