# Generated by Django 3.1.5 on 2021-02-01 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_eng_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdcompany_eng',
            name='company_zipcode',
            field=models.CharField(db_column='company_zipcode', default='Null', max_length=255),
        ),
        migrations.AddField(
            model_name='dbdcompany_eng',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_address',
            field=models.TextField(db_column='company_address', default='Null'),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_bussiness_type',
            field=models.TextField(db_column='company_bussiness_type', default='Null'),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_bussiness_type_code',
            field=models.CharField(db_column='company_bussiness_code', default='Null', max_length=20),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_district',
            field=models.CharField(db_column='company_district', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_email',
            field=models.CharField(db_column='company_email', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_fax',
            field=models.CharField(db_column='company_fax', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_name',
            field=models.CharField(db_column='company_name', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_objective',
            field=models.TextField(db_column='company_objective', default='Null'),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_province',
            field=models.CharField(db_column='company_province', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_status',
            field=models.CharField(db_column='company_status', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_street',
            field=models.TextField(db_column='company_street', default='Null'),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_subdistrict',
            field=models.CharField(db_column='company_subdistrict', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_tel',
            field=models.CharField(db_column='company_tel', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_type',
            field=models.CharField(db_column='company_type', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_website',
            field=models.CharField(db_column='company_website', default='Null', max_length=255),
        ),
    ]
