# Generated by Django 3.1.5 on 2021-02-03 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_eng_app', '0002_auto_20210201_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbdcompany_eng',
            name='company_district',
        ),
        migrations.RemoveField(
            model_name='dbdcompany_eng',
            name='company_province',
        ),
        migrations.RemoveField(
            model_name='dbdcompany_eng',
            name='company_street',
        ),
        migrations.RemoveField(
            model_name='dbdcompany_eng',
            name='company_subdistrict',
        ),
        migrations.RemoveField(
            model_name='dbdcompany_eng',
            name='company_zipcode',
        ),
        migrations.RemoveField(
            model_name='dbdcompany_eng',
            name='date',
        ),
        migrations.AddField(
            model_name='dbdcompany_eng',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dbdcompany_eng',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dbdcompany_eng',
            name='company_id',
            field=models.CharField(db_column='company_id', default='Null', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
