# Generated by Django 3.1.5 on 2021-03-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatioYearDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, db_column='company_id', max_length=20, null=True)),
                ('year', models.CharField(blank=True, db_column='year', max_length=20, null=True)),
                ('ratio', models.CharField(blank=True, db_column='ratio', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Ratio Year Details',
                'verbose_name_plural': 'Scraped Eng Ratio Year Detail',
                'db_table': 'ratio_year_detail_eng',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PRDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, db_column='company_id', max_length=20, null=True)),
                ('gross_profit_mar', models.ManyToManyField(blank=True, db_column='gross_profit_mar', max_length=255, related_name='gross_profit_mar', to='finan_ratio_app.RatioYearDetail')),
                ('net_profit_mar', models.ManyToManyField(blank=True, db_column='net_profit_mar', max_length=255, related_name='net_profit_mar', to='finan_ratio_app.RatioYearDetail')),
                ('opera_inc_on_reve_r', models.ManyToManyField(blank=True, db_column='opera_inc_on_reve_r', max_length=255, related_name='opera_inc_on_reve_r', to='finan_ratio_app.RatioYearDetail')),
                ('ret_on_asset', models.ManyToManyField(blank=True, db_column='ret_on_asset', max_length=255, related_name='ret_on_asset', to='finan_ratio_app.RatioYearDetail')),
                ('ret_on_equity', models.ManyToManyField(blank=True, db_column='ret_on_equity', max_length=255, related_name='ret_on_equity', to='finan_ratio_app.RatioYearDetail')),
            ],
            options={
                'verbose_name': 'Profit Ratio Details',
                'verbose_name_plural': 'Scraped Eng Profit Ratio Detail',
                'db_table': 'profit_ratio_detail_eng',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OERDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, db_column='company_id', max_length=20, null=True)),
                ('opera_expe_to_t_reve_r', models.ManyToManyField(blank=True, db_column='opera_expe_to_t_reve_r', max_length=255, related_name='opera_expe_to_t_reve_r', to='finan_ratio_app.RatioYearDetail')),
                ('t_asset_tur', models.ManyToManyField(blank=True, db_column='t_asset_tur', max_length=255, related_name='t_asset_tur', to='finan_ratio_app.RatioYearDetail')),
            ],
            options={
                'verbose_name': 'Operat Effici Ratio Details',
                'verbose_name_plural': 'Scraped Eng Operat Effici Ratio Detail',
                'db_table': 'operat_effici_ratio_detail_eng',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LRDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, db_column='company_id', max_length=20, null=True)),
                ('acco_pay_tur', models.ManyToManyField(blank=True, db_column='acco_pay_tur', max_length=255, related_name='acco_pay_tur', to='finan_ratio_app.RatioYearDetail')),
                ('acco_recei_tur', models.ManyToManyField(blank=True, db_column='acco_recei_tur', max_length=255, related_name='acco_recei_tur', to='finan_ratio_app.RatioYearDetail')),
                ('curr_r', models.ManyToManyField(blank=True, db_column='curr_r', max_length=255, related_name='curr_r', to='finan_ratio_app.RatioYearDetail')),
                ('invent_tur', models.ManyToManyField(blank=True, db_column='invent_tur', max_length=255, related_name='invent_tur', to='finan_ratio_app.RatioYearDetail')),
            ],
            options={
                'verbose_name': 'Liquid Ratio Details',
                'verbose_name_plural': 'Scraped Eng Liquid Ratio Detail',
                'db_table': 'liquid_ratio_detail_eng',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FPPRDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, db_column='company_id', max_length=20, null=True)),
                ('asse_to_equi_r_finan_lev', models.ManyToManyField(blank=True, db_column='asse_to_equi_r_finan_lev', max_length=255, related_name='asse_to_equi_r_finan_lev', to='finan_ratio_app.RatioYearDetail')),
                ('debt_to_asse_r', models.ManyToManyField(blank=True, db_column='debt_to_asse_r', max_length=255, related_name='debt_to_asse_r', to='finan_ratio_app.RatioYearDetail')),
                ('debt_to_capi_r', models.ManyToManyField(blank=True, db_column='debt_to_capi_r', max_length=255, related_name='debt_to_capi_r', to='finan_ratio_app.RatioYearDetail')),
                ('debt_to_equi_r', models.ManyToManyField(blank=True, db_column='debt_to_equi_r', max_length=255, related_name='debt_to_equi_r', to='finan_ratio_app.RatioYearDetail')),
            ],
            options={
                'verbose_name': 'Finan Posit Propo Ratio Details',
                'verbose_name_plural': 'Scraped Eng Finan Posit Propo Ratio Detail',
                'db_table': 'finan_posit_propo_ratio_detail_eng',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FinancialRatio',
            fields=[
                ('company_id', models.CharField(db_column='company_id', default='Null', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('finan_posit_propo_r', models.ManyToManyField(blank=True, db_column='finan_posit_propo_r', max_length=255, related_name='finan_posit_propo_r', to='finan_ratio_app.FPPRDetail')),
                ('liquid_r', models.ManyToManyField(blank=True, db_column='liquid_r', max_length=255, related_name='liquid_r', to='finan_ratio_app.LRDetail')),
                ('operat_effici_r', models.ManyToManyField(blank=True, db_column='operat_effici_r', max_length=255, related_name='operat_effici_r', to='finan_ratio_app.OERDetail')),
                ('profit_r', models.ManyToManyField(blank=True, db_column='profit_r', max_length=255, related_name='profit_r', to='finan_ratio_app.PRDetail')),
            ],
            options={
                'verbose_name': 'Financial Ratios',
                'verbose_name_plural': 'Scraped Eng Financial Ratio',
                'db_table': 'finian_ratio_eng',
                'managed': True,
            },
        ),
    ]
