# Generated by Django 3.1.5 on 2021-01-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBDCompany_Thai',
            fields=[
                ('company_id', models.CharField(db_column='company_id', max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='company_name', max_length=255)),
                ('company_type', models.CharField(db_column='company_type', max_length=255)),
                ('company_status', models.CharField(db_column='company_status', max_length=255)),
                ('company_objective', models.CharField(db_column='company_objective', max_length=255)),
                ('company_directors', models.CharField(db_column='company_directors', max_length=255)),
                ('company_bussiness_type', models.CharField(db_column='company_bussiness_type', max_length=255)),
                ('company_bussiness_type_code', models.CharField(db_column='company_bussiness_code', max_length=20)),
                ('company_street', models.CharField(db_column='company_street', max_length=255)),
                ('company_subdistrict', models.CharField(db_column='company_subdistrict', max_length=255)),
                ('company_district', models.CharField(db_column='company_district', max_length=255)),
                ('company_province', models.CharField(db_column='company_province', max_length=255)),
                ('company_address', models.CharField(db_column='company_address', max_length=255)),
                ('company_tel', models.CharField(db_column='company_tel', max_length=255)),
                ('company_fax', models.CharField(db_column='company_fax', max_length=255)),
                ('company_website', models.CharField(db_column='company_website', max_length=255)),
                ('company_email', models.CharField(db_column='company_email', max_length=255)),
            ],
            options={
                'verbose_name': 'Scraped Company',
                'verbose_name_plural': 'Scraped Thai Companies',
                'db_table': 'dbd_scraped_company_thai',
                'managed': True,
            },
        ),
    ]
