# Generated by Django 3.1.5 on 2021-01-25 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_thai_app', '0002_auto_20210122_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdcompany_thai',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
