# Generated by Django 3.1.5 on 2021-01-29 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_thai_app', '0003_dbdcompany_thai_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdcompany_thai',
            name='company_fiscal_year',
            field=models.CharField(db_column='company_fiscal_year', default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dbdcompany_thai',
            name='company_last_registered_id',
            field=models.CharField(db_column='company_last_registered_id', default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
