# Generated by Django 3.1.5 on 2021-01-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_thai_app', '0004_auto_20210129_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_last_registered_id',
            field=models.CharField(db_column='company_last_registered_id', max_length=20),
        ),
    ]
