# Generated by Django 3.1.5 on 2021-02-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_thai_app', '0005_auto_20210129_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdcompany_thai',
            name='company_zipcode',
            field=models.CharField(db_column='company_zipcode', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_address',
            field=models.TextField(db_column='company_address', default='Null'),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_bussiness_type',
            field=models.TextField(db_column='company_bussiness_type', default='Null'),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_bussiness_type_code',
            field=models.CharField(db_column='company_bussiness_code', default='Null', max_length=20),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_district',
            field=models.CharField(db_column='company_district', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_email',
            field=models.CharField(db_column='company_email', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_fax',
            field=models.CharField(db_column='company_fax', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_fiscal_year',
            field=models.CharField(db_column='company_fiscal_year', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_id',
            field=models.CharField(db_column='company_id', default='Null', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_last_registered_id',
            field=models.CharField(db_column='company_last_registered_id', default='Null', max_length=20),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_name',
            field=models.CharField(db_column='company_name', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_objective',
            field=models.TextField(db_column='company_objective', default='Null'),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_province',
            field=models.CharField(db_column='company_province', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_status',
            field=models.CharField(db_column='company_status', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_street',
            field=models.TextField(db_column='company_street', default='Null'),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_subdistrict',
            field=models.CharField(db_column='company_subdistrict', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_tel',
            field=models.CharField(db_column='company_tel', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_type',
            field=models.CharField(db_column='company_type', default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_website',
            field=models.CharField(db_column='company_website', default='Null', max_length=255),
        ),
    ]
