# Generated by Django 3.1.5 on 2021-02-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_thai_app', '0006_auto_20210201_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='company_id',
            field=models.CharField(db_column='company_id', default='Null', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
