# Generated by Django 3.1.5 on 2021-02-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_thai_app', '0007_auto_20210202_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbdcompany_thai',
            name='company_zipcode',
        ),
    ]
