# Generated by Django 3.1.5 on 2021-02-02 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_thai_app', '0008_remove_dbdcompany_thai_company_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbdcompany_thai',
            name='date',
        ),
        migrations.AddField(
            model_name='dbdcompany_thai',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dbdcompany_thai',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
