# Generated by Django 3.1.5 on 2021-02-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_thai_app', '0009_auto_20210202_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbdcompany_thai',
            old_name='timestamp',
            new_name='created',
        ),
    ]
