# Generated by Django 3.1.5 on 2021-02-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_thai_app', '0010_auto_20210202_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbdcompany_thai',
            name='updated',
        ),
        migrations.AddField(
            model_name='dbdcompany_thai',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
