# Generated by Django 3.1.5 on 2021-02-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_thai_app', '0012_auto_20210202_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbdcompany_thai',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
