# Generated by Django 3.1.5 on 2021-04-09 07:09

from django.db import migrations, models
import file_manage_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=32)),
                ('file', models.FileField(blank=True, null=True, upload_to=file_manage_app.models.upload_path)),
                ('filename', models.CharField(max_length=32)),
            ],
        ),
    ]
