# Generated by Django 3.1.5 on 2021-02-24 16:39

from django.db import migrations, models
import file_manage_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=file_manage_app.models.upload_path),
        ),
    ]
