# Generated by Django 3.1.5 on 2021-03-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage_app', '0003_auto_20210301_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
