# Generated by Django 3.1.5 on 2021-03-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeYearDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, db_column='company_id', max_length=20, null=True)),
                ('year', models.CharField(blank=True, db_column='year', max_length=20, null=True)),
                ('amount', models.CharField(blank=True, db_column='amount', max_length=40, null=True)),
                ('change', models.CharField(blank=True, db_column='change', max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Income Year Details',
                'verbose_name_plural': 'Scraped Eng Income Year Detail',
                'db_table': 'income_year_detail_eng',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IncomeStat',
            fields=[
                ('company_id', models.CharField(db_column='company_id', default='Null', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('cost_of_goods_sold', models.ManyToManyField(blank=True, db_column='cost_of_goods_sold', max_length=255, related_name='cost_of_goods_sold', to='income_state_app.IncomeYearDetail')),
                ('gross_profit', models.ManyToManyField(blank=True, db_column='gross_profit', max_length=255, related_name='gross_profit', to='income_state_app.IncomeYearDetail')),
                ('income_tax_expe', models.ManyToManyField(blank=True, db_column='income_tax_expe', max_length=255, related_name='income_tax_expe', to='income_state_app.IncomeYearDetail')),
                ('intere_expe', models.ManyToManyField(blank=True, db_column='intere_expe', max_length=255, related_name='intere_expe', to='income_state_app.IncomeYearDetail')),
                ('net_profit', models.ManyToManyField(blank=True, db_column='net_profit', max_length=255, related_name='net_profit', to='income_state_app.IncomeYearDetail')),
                ('profit_before_income_tax', models.ManyToManyField(blank=True, db_column='profit_before_income_tax', max_length=255, related_name='profit_before_income_tax', to='income_state_app.IncomeYearDetail')),
                ('reve_from_sale_serv', models.ManyToManyField(blank=True, db_column='reve_from_sale_serv', max_length=255, related_name='reve_from_sale_serv', to='income_state_app.IncomeYearDetail')),
                ('sell_admin_expe', models.ManyToManyField(blank=True, db_column='sell_admin_expe', max_length=255, related_name='sell_admin_expe', to='income_state_app.IncomeYearDetail')),
                ('t_expe', models.ManyToManyField(blank=True, db_column='t_expe', max_length=255, related_name='t_expe', to='income_state_app.IncomeYearDetail')),
                ('t_reve', models.ManyToManyField(blank=True, db_column='t_reve', max_length=255, related_name='t_reve', to='income_state_app.IncomeYearDetail')),
            ],
            options={
                'verbose_name': 'Income Statements',
                'verbose_name_plural': 'Scraped Eng Income Statement',
                'db_table': 'income_statement_eng',
                'managed': True,
            },
        ),
    ]
