CREATE DATABASE IF NOT EXISTS companies;

USE companies;

CREATE TABLE `all_companies` (
  `COMPANY_NAME` varchar(225) DEFAULT NULL,
  `COMPANY_ID` varchar(225) NOT NULL,
  `COMPANY_TYPE` varchar(225) DEFAULT NULL,
  `COMPANY_STATUS` varchar(225) DEFAULT NULL,
  `COMPANY_ADDRESS` text DEFAULT NULL,
  `COMPANY_OBJECTIVE` varchar(225) DEFAULT NULL,
  `COMPANY_DIRECTORS` text DEFAULT NULL,
  `COMPANY_BUSINESS_TYPE` varchar(225) DEFAULT NULL,
  `COMPANY_BUSINESS_TYPE_CODE` varchar(225) DEFAULT NULL,
  `COMPANY_STREET` text DEFAULT NULL,
  `COMPANY_SUBDISTRICT` varchar(225) DEFAULT NULL,
  `COMPANY_DISTRICT` varchar(225) DEFAULT NULL,
  `COMPANY_PROVINCE` varchar(225) DEFAULT NULL,
  `TEL` varchar(225) DEFAULT NULL,
  `FAX` varchar(225) DEFAULT NULL,
  `WEBSITE` text DEFAULT NULL,
  `EMAIL` varchar(225) DEFAULT NULL,
  `DATE_CREATED` date DEFAULT NULL,
  PRIMARY KEY (`COMPANY_ID`),
  UNIQUE KEY `dbd_id_UNIQUE` (`COMPANY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `test_companies_thai` (
  `COMPANY_NAME` varchar(225) DEFAULT NULL,
  `COMPANY_ID` varchar(225) NOT NULL,
  `COMPANY_TYPE` varchar(225) DEFAULT NULL,
  `COMPANY_STATUS` varchar(225) DEFAULT NULL,
  `COMPANY_ADDRESS` text DEFAULT NULL,
  `COMPANY_OBJECTIVE` varchar(225) DEFAULT NULL,
  `COMPANY_DIRECTORS` text DEFAULT NULL,
  `COMPANY_BUSINESS_TYPE` varchar(225) DEFAULT NULL,
  `COMPANY_BUSINESS_TYPE_CODE` varchar(225) DEFAULT NULL,
  `COMPANY_STREET` text DEFAULT NULL,
  `COMPANY_SUBDISTRICT` varchar(225) DEFAULT NULL,
  `COMPANY_DISTRICT` varchar(225) DEFAULT NULL,
  `COMPANY_PROVINCE` varchar(225) DEFAULT NULL,
  `TEL` varchar(225) DEFAULT NULL,
  `FAX` varchar(225) DEFAULT NULL,
  `WEBSITE` text DEFAULT NULL,
  `EMAIL` varchar(225) DEFAULT NULL,
  `DATE_CREATED` date DEFAULT NULL,
  PRIMARY KEY (`COMPANY_ID`),
  UNIQUE KEY `dbd_id_UNIQUE` (`COMPANY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `test_companies_eng` (
  `COMPANY_NAME` varchar(225) DEFAULT NULL,
  `COMPANY_ID` varchar(225) NOT NULL,
  `COMPANY_TYPE` varchar(225) DEFAULT NULL,
  `COMPANY_STATUS` varchar(225) DEFAULT NULL,
  `COMPANY_ADDRESS` text DEFAULT NULL,
  `COMPANY_OBJECTIVE` varchar(225) DEFAULT NULL,
  `COMPANY_DIRECTORS` text DEFAULT NULL,
  `COMPANY_BUSINESS_TYPE` varchar(225) DEFAULT NULL,
  `COMPANY_BUSINESS_TYPE_CODE` varchar(225) DEFAULT NULL,
  `COMPANY_STREET` text DEFAULT NULL,
  `COMPANY_SUBDISTRICT` varchar(225) DEFAULT NULL,
  `COMPANY_DISTRICT` varchar(225) DEFAULT NULL,
  `COMPANY_PROVINCE` varchar(225) DEFAULT NULL,
  `TEL` varchar(225) DEFAULT NULL,
  `FAX` varchar(225) DEFAULT NULL,
  `WEBSITE` text DEFAULT NULL,
  `EMAIL` varchar(225) DEFAULT NULL,
  `DATE_CREATED` date DEFAULT NULL,
  PRIMARY KEY (`COMPANY_ID`),
  UNIQUE KEY `dbd_id_UNIQUE` (`COMPANY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

